package preferences

var preferenceMap = map[string]Preference{
	"ORG_ONBOARDING": {
		Key:              "ORG_ONBOARDING",
		Name:             "Organisation Onboarding",
		Description:      "Organisation Onboarding",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"org"},
	},
	"WELCOME_CHECKLIST_DO_LATER": {
		Key:              "WELCOME_CHECKLIST_DO_LATER",
		Name:             "Welcome Checklist Do Later",
		Description:      "Welcome Checklist Do Later",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SEND_LOGS_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SEND_LOGS_SKIPPED",
		Name:             "Welcome Checklist Send Logs Skipped",
		Description:      "Welcome Checklist Send Logs Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SEND_TRACES_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SEND_TRACES_SKIPPED",
		Name:             "Welcome Checklist Send Traces Skipped",
		Description:      "Welcome Checklist Send Traces Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SEND_INFRA_METRICS_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SEND_INFRA_METRICS_SKIPPED",
		Name:             "Welcome Checklist Send Infra Metrics Skipped",
		Description:      "Welcome Checklist Send Infra Metrics Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SETUP_DASHBOARDS_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SETUP_DASHBOARDS_SKIPPED",
		Name:             "Welcome Checklist Setup Dashboards Skipped",
		Description:      "Welcome Checklist Setup Dashboards Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SETUP_ALERTS_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SETUP_ALERTS_SKIPPED",
		Name:             "Welcome Checklist Setup Alerts Skipped",
		Description:      "Welcome Checklist Setup Alerts Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
	"WELCOME_CHECKLIST_SETUP_SAVED_VIEW_SKIPPED": {
		Key:              "WELCOME_CHECKLIST_SETUP_SAVED_VIEW_SKIPPED",
		Name:             "Welcome Checklist Setup Saved View Skipped",
		Description:      "Welcome Checklist Setup Saved View Skipped",
		ValueType:        "boolean",
		DefaultValue:     false,
		AllowedValues:    []interface{}{true, false},
		IsDiscreteValues: true,
		AllowedScopes:    []string{"user"},
	},
}
