#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Convert $1 to absolute path before cd
commit_msg_file="$(realpath "$1")"

cd frontend && yarn run commitlint "$commit_msg_file"

branch="$(git rev-parse --abbrev-ref HEAD)"

color_red="$(tput setaf 1)"
bold="$(tput bold)"
reset="$(tput sgr0)"

if [ "$branch" = "main" ]; then
  echo "${color_red}${bold}You can't commit directly to the main branch${reset}"
  exit 1
fi
