const createdByEmail = 'mando@signoz.io';

export const getAPIKeysResponse = {
	status: 'success',
	data: [
		{
			id: '26',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'T2DuASwpuUx3wlYraFl5r7N9G1ikBhzGuy2ihcIKDMs=',
			role: 'ADMIN',
			name: '1 Day Old',
			createdAt: 1708010258,
			expiresAt: 1708096658,
			updatedAt: 1708010258,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '24',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'EteVs77BA4FFLJD/TsFE9c+CLX4kXVmlx+0GGK7dpXY=',
			role: 'ADMIN',
			name: '1 year expiry - updated',
			createdAt: 1708008146,
			expiresAt: 1739544146,
			updatedAt: 1708008239,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '25',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: '1udrUFmRI6gdb8r/hLabS7zRlgfMQlUw/tz9sac82pE=',
			role: 'ADMIN',
			name: 'No Expiry Key',
			createdAt: 1708008178,
			expiresAt: 0,
			updatedAt: 1708008190,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '22',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'gtqKF7g7avoe+Yu2+WhyDDLQSr6IsVaR5xpby2XhLAY=',
			role: 'VIEWER',
			name: 'No Expiry',
			createdAt: 1708007395,
			expiresAt: 0,
			updatedAt: 1708007936,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '23',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'GM/TqEID8N4ynlvQHK38ITEvRAcn5XkJZpmd11xT3OQ=',
			role: 'VIEWER',
			name: 'No Expiry - 2',
			createdAt: 1708007685,
			expiresAt: 0,
			updatedAt: 1708007786,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '19',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'Oj75e6Zr7JmjFcWIo0UK/Nl06RdC2BKOr/QVHoBA0gM=',
			role: 'ADMIN',
			name: '7 Days',
			createdAt: 1708003326,
			expiresAt: 1708608126,
			updatedAt: 1708007380,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '20',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'T+sNdYe6I74ya/9mEKqB3UTrFm8+jwI0DiirqEx3bsM=',
			role: 'EDITOR',
			name: '1 month',
			createdAt: 1708004012,
			expiresAt: 1710596012,
			updatedAt: 1708005206,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '21',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'JWw26FuymeHq+fsfFcb+2+Ls/MdokmeXxXdZisuaVeI=',
			role: 'ADMIN',
			name: '3 Months',
			createdAt: 1708004755,
			expiresAt: 1715780755,
			updatedAt: 1708005197,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
		{
			id: '17',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '2zDrYNr+IWXUyA14+afVvO6GI9dcHfEsOYxjA9mrprg=',
			role: 'ADMIN',
			name: 'New No Expiry',
			createdAt: 1708000444,
			expiresAt: 0,
			updatedAt: 1708000444,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '14',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'Q+/+UB2OrDPcS9b0+5A1dDXYmWHz0abbVVidF48QCso=',
			role: 'EDITOR',
			name: 'Editor Token for user 1',
			createdAt: 1707997720,
			expiresAt: 1708170520,
			updatedAt: 1707997720,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '13',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: '/X3OEaSOLrrJImvzIB3g5WGg+5831X89fZZQT1JaxvQ=',
			role: 'EDITOR',
			name: 'Editor Token for user 2',
			createdAt: 1707997603,
			expiresAt: 1708170403,
			updatedAt: 1707997603,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '12',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'bTs+Q6waIiP4KJ8L5N58EQonuapWMXsfEra/cmMwmbE=',
			role: 'EDITOR',
			name: 'Editor Token for user 3',
			createdAt: 1707997539,
			expiresAt: 1708170339,
			updatedAt: 1707997539,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '11',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'YaEqQHrH8KOnYFllor/8Tq653TgxPU1Z7ZDzY3+ETmI=',
			role: 'EDITOR',
			name: 'Editor Token for user',
			createdAt: 1707997537,
			expiresAt: 1708170337,
			updatedAt: 1707997537,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '10',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'Hg/QpMU9VQyqIuzSh9ND2454IN5uOHzVkv7owEtBcPo=',
			role: 'EDITOR',
			name: 'test123',
			createdAt: 1707997288,
			expiresAt: 1708083688,
			updatedAt: 1707997288,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '9',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'M5gMsccDthPTibquB7kR7ZSEI76y4endOxZPESZ9/po=',
			role: 'VIEWER',
			name: 'Viewer Token for user',
			createdAt: 1707996747,
			expiresAt: 1708255947,
			updatedAt: 1707996747,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '8',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'H8NVlOD09IcMgQ/rzfVucb+4+jEcqZ4ZRx6n7QztMSc=',
			role: 'EDITOR',
			name: 'Editor Token for user',
			createdAt: 1707996736,
			expiresAt: 1708169536,
			updatedAt: 1707996736,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '7',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '',
				name: '',
				email: '',
				createdAt: 0,
				profilePictureURL: '',
				notFound: true,
			},
			token: 'z24SswLmNlPVUgb1j6rfc2u4Kb4xSUolwb11cI8kbrs=',
			role: 'ADMIN',
			name: 'Admin Token for user',
			createdAt: 1707996719,
			expiresAt: 0,
			updatedAt: 1707996719,
			lastUsed: 0,
			revoked: false,
			updatedByUserId: '',
		},
		{
			id: '5',
			userId: 'mandalorian',
			createdByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			updatedByUser: {
				id: '001',
				name: 'Mando',
				email: createdByEmail,
				createdAt: 1707974098,
				profilePictureURL: '',
				notFound: false,
			},
			token: 'SWuNSF08EB6+VN05312QaAsPum2wkqIm+ujiWZKnm2Q=',
			role: 'EDITOR',
			name: 'Editor Token',
			createdAt: 1707992270,
			expiresAt: 1708165070,
			updatedAt: 1707995424,
			lastUsed: 1707992517,
			revoked: false,
			updatedByUserId: 'mandalorian',
		},
	],
};

export const createAPIKeyResponse = {
	status: 'success',
	data: {
		id: '57',
		userId: 'mandalorian',
		token: 'pQ5kiHjcbQ2FbKlS14LQjA2RzXEBi/KvBfM7BRSwltI=',
		name: 'test1233',
		createdAt: 1707818550,
		expiresAt: 0,
	},
};
