// Code generated by scripts/semconv. DO NOT EDIT.

package semconv

var families = []Family{
	{
		Current:        "db.system.name",
		Old:            []string{"db.system"},
		Kind:           KindAttribute,
		Contexts:       nil,
		Signals:        nil,
		ApplyToMetrics: nil,
	},
	{
		Current:        "deployment.environment.name",
		Old:            []string{"deployment.environment"},
		Kind:           KindAttribute,
		Contexts:       nil,
		Signals:        nil,
		ApplyToMetrics: nil,
	},
}
