export enum VIEWS {
	ALL_ENDPOINTS = 'all_endpoints',
	ENDPOINT_STATS = 'endpoint_stats',
	TOP_ERRORS = 'top_errors',
}

export const VIEW_TYPES = {
	ALL_ENDPOINTS: VIEWS.ALL_ENDPOINTS,
	ENDPOINT_STATS: VIEWS.ENDPOINT_STATS,
	TOP_ERRORS: VIEWS.TOP_ERRORS,
};
