"""
Upstream promqltest conformance: replay the frozen corpus extracted from
Prometheus' own promql/promqltest testdata and assert our API returns the
reference engine's answers.

Unlike the parity suites, the oracle here is a committed file
(tests/integration/testdata/promqltestcorpus/corpus.json), generated by
scripts/promqltestcorpus from upstream's load scripts and the vendored
reference engine. It therefore keeps working when the serving path itself is
the thing being changed — the one situation where comparing two live paths
against each other is blind.

Datasets are placed on disjoint time windows (2h isolation gaps, far beyond
the 5m lookback) so one bulk ingest serves every case without cross-talk.
Expected values carry the API's 3-significant-decimal rounding, mirrored by
the generator; comparison allows one rounding quantum for ULP-at-boundary
noise between storage iteration orders.
"""

import json
import math
import os
from collections.abc import Callable
from datetime import UTC, datetime, timedelta
from http import HTTPStatus

from fixtures import types
from fixtures.auth import USER_ADMIN_EMAIL, USER_ADMIN_PASSWORD
from fixtures.metrics import Metrics
from fixtures.querier import get_all_series, make_query_request

TESTDATA_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "testdata")
CORPUS_FILE = os.path.join(TESTDATA_DIR, "promqltestcorpus", "corpus.json")
KNOWN_DIVERGENCES_FILE = os.path.join(TESTDATA_DIR, "promqltestcorpus", "known_divergences.json")

ISOLATION_GAP_MS = 2 * 3600 * 1000
SPECIALS = {"NaN": math.nan, "Inf": math.inf, "-Inf": -math.inf}


def _values_close(a: float, b: float) -> bool:
    if math.isnan(a) or math.isnan(b):
        return math.isnan(a) and math.isnan(b)
    if math.isinf(a) or math.isinf(b):
        return a == b
    if a == b:
        return True
    # Both sides carry the API's rounding (>=1: three decimal places; <1:
    # three significant digits). A true value sitting exactly on a rounding
    # boundary can round either way when the two computations differ at ULP
    # level (float aggregation order over series is storage-iteration
    # dependent), so allow one rounding quantum.
    scale = max(abs(a), abs(b))
    if scale >= 1:
        # Values too large to round pass through unrounded; give those an
        # ULP-class relative grace on top of the rounding quantum.
        quantum = max(1e-3, scale * 1e-9)
    else:
        quantum = 10 ** (math.floor(math.log10(scale)) - 2)
    return abs(a - b) <= quantum + 1e-12


def _response_series(data: dict) -> tuple[dict[tuple, dict[int, float]], list[tuple]]:
    """Returns (series map, duplicate labelsets). A response carrying several
    series with identical visible labels is itself a defect signal (e.g. a
    hidden grouping label stripped on the way out) and must not be silently
    collapsed into one entry."""
    out: dict[tuple, dict[int, float]] = {}
    duplicates: list[tuple] = []
    # Empty results serialize with null aggregations/series/values fields.
    for series in get_all_series(data, "A") or []:
        lbls = {l["key"]["name"]: str(l["value"]) for l in series.get("labels") or []}
        points = {int(v["timestamp"]): SPECIALS[v["value"]] if isinstance(v["value"], str) else float(v["value"]) for v in series.get("values") or []}
        key = tuple(sorted(lbls.items()))
        if key in out:
            duplicates.append(key)
        out[key] = points
    return out, duplicates


def test_upstream_promqltest_corpus(
    signoz: types.SigNoz,
    create_user_admin: None,  # pylint: disable=unused-argument
    get_token: Callable[[str, str], str],
    insert_metrics: Callable[[list[Metrics]], None],
) -> None:
    with open(CORPUS_FILE, encoding="utf-8") as f:
        corpus = json.load(f)

    cases_by_dataset: dict[int, list[dict]] = {}
    for case in corpus["cases"]:
        cases_by_dataset.setdefault(case["dataset"], []).append(case)

    # Lay datasets end to end on the timeline, newest last, ending safely in
    # the past; spans are per-dataset so the whole corpus stays within days.
    spans = {}
    for ds in corpus["datasets"]:
        sample_max = max((s["samples"][-1][0] for s in ds["series"] if s["samples"]), default=0)
        case_max = max((c["end_ms"] for c in cases_by_dataset.get(ds["id"], [])), default=0)
        spans[ds["id"]] = max(sample_max, case_max) + corpus["meta"]["lookback_ms"]

    # Hour-aligned dataset bases: registration rows are hour-bucketed, so
    # behavior depends on where samples fall relative to hour boundaries —
    # the exact known-divergences enforcement needs that identical every run.
    hour_ms = 3_600_000
    advances = {ds["id"]: -(-(spans[ds["id"]] + ISOLATION_GAP_MS) // hour_ms) * hour_ms for ds in corpus["datasets"]}
    total = sum(advances.values())
    now = datetime.now(tz=UTC).replace(second=0, microsecond=0)
    cursor = (int((now - timedelta(hours=1)).timestamp() * 1000) - total) // hour_ms * hour_ms

    bases: dict[int, int] = {}
    metrics: list[Metrics] = []
    for ds in corpus["datasets"]:
        bases[ds["id"]] = cursor
        for series in ds["series"]:
            labels = dict(series["labels"])
            metric_name = labels.pop("__name__")
            for off_ms, raw in series["samples"]:
                stale = raw == "stale"
                metrics.append(
                    Metrics(
                        metric_name=metric_name,
                        labels=labels,
                        timestamp=datetime.fromtimestamp((cursor + off_ms) / 1000, tz=UTC),
                        value=0.0 if stale else (SPECIALS[raw] if isinstance(raw, str) else float(raw)),
                        flags=1 if stale else 0,
                    )
                )
        cursor += advances[ds["id"]]

    insert_metrics(metrics)
    token = get_token(USER_ADMIN_EMAIL, USER_ADMIN_PASSWORD)

    failures: list[str] = []
    for case in corpus["cases"]:
        base = bases[case["dataset"]]
        start_ms = base + case["start_ms"]
        end_ms = base + case["end_ms"]
        step_s = max(1, case["step_ms"] // 1000)
        req_start_ms = start_ms
        if case["instant"]:
            # The API rejects start == end; ask for one extra step backward
            # and compare only at the instant timestamp. Nudging the start
            # earlier instead of the end later keeps every window that the
            # expected values were computed from untouched.
            req_start_ms = start_ms - step_s * 1000
        query = {
            "type": "promql",
            "spec": {"name": "A", "query": case["expr"], "step": step_s},
        }

        case_id = f"{case['source']}[{case['variant']}]"
        response = make_query_request(signoz, token, req_start_ms, end_ms, [query])
        if response.status_code != HTTPStatus.OK:
            failures.append(f"{case_id}: HTTP {response.status_code} for {case['expr']!r}: {response.text[:200]}")
            continue

        actual, duplicates = _response_series(response.json())
        if duplicates:
            failures.append(f"{case_id}: response carries multiple series with identical labels for {case['expr']!r}: {[dict(d) for d in duplicates[:3]]}")
            continue
        if case["instant"]:
            # Keep only the instant point; the extra grid step is a request
            # encoding byproduct, not part of the assertion.
            actual = {lset: {ts: v for ts, v in pts.items() if ts == end_ms} for lset, pts in actual.items()}
            actual = {lset: pts for lset, pts in actual.items() if pts}
        expected: dict[tuple, dict[int, float]] = {}
        for res in case["expected"]:
            points = {base + off_ms: SPECIALS[v] if isinstance(v, str) else float(v) for off_ms, v in res["points"]}
            expected[tuple(sorted(res["labels"].items()))] = points

        if set(actual) != set(expected):
            missing = set(expected) - set(actual)
            extra = set(actual) - set(expected)
            failures.append(f"{case_id}: series mismatch for {case['expr']!r} (missing={sorted(missing)[:3]} extra={sorted(extra)[:3]}) actual={[(dict(k), {t - base: v for t, v in pts.items()}) for k, pts in actual.items()]}")
            continue

        for lset, exp_points in expected.items():
            act_points = actual[lset]
            if set(act_points) != set(exp_points):
                failures.append(f"{case_id}: timestamp mismatch for {case['expr']!r} series {dict(lset)} (expected {len(exp_points)} points, got {len(act_points)})")
                break
            for ts, exp_v in exp_points.items():
                if not _values_close(act_points[ts], exp_v):
                    failures.append(f"{case_id}: value mismatch for {case['expr']!r} series {dict(lset)} at {ts}: expected {exp_v}, got {act_points[ts]}")
                    break
            else:
                continue
            break

    for f_line in failures:
        print("DIVERGED", f_line)

    # Known divergences are defects of the current serving path, frozen with
    # reasons. The set is enforced exactly in both directions: a NEW
    # divergence is a regression, and a known divergence that starts passing
    # must be removed from the file — that is the ledger the serving-path
    # swap is measured against.
    known: dict[str, str] = {}
    if os.path.exists(KNOWN_DIVERGENCES_FILE):
        with open(KNOWN_DIVERGENCES_FILE, encoding="utf-8") as f:
            known = json.load(f)["divergences"]

    failed_ids = {f_line.split(": ", 1)[0] for f_line in failures}
    unexpected = [f_line for f_line in failures if f_line.split(": ", 1)[0] not in known]
    now_passing = sorted(set(known) - failed_ids)

    assert not unexpected, f"{len(unexpected)} corpus cases diverged beyond the known set:\n" + "\n".join(unexpected[:25])
    assert not now_passing, f"{len(now_passing)} known divergences now pass — remove them from known_divergences.json: {now_passing[:25]}"
