import { domainNameKey } from '../constants';
import { APIMonitoringResponseColumn } from '../types';

export const APIMonitoringColumnsMock: APIMonitoringResponseColumn[] = [
	{
		name: domainNameKey,
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'string',
		queryName: '',
		aggregationIndex: 0,
		meta: {},
		columnType: 'attribute',
	},
	{
		name: 'endpoints',
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'number',
		queryName: 'endpoints',
		aggregationIndex: 0,
		meta: {},
		columnType: 'metric',
	},
	{
		name: 'rps',
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'number',
		queryName: 'rps',
		aggregationIndex: 0,
		meta: {},
		columnType: 'metric',
	},
	{
		name: 'error_rate',
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'number',
		queryName: 'error_rate',
		aggregationIndex: 0,
		meta: {},
		columnType: 'metric',
	},
	{
		name: 'p99',
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'number',
		queryName: 'p99',
		aggregationIndex: 0,
		meta: {},
		columnType: 'metric',
	},
	{
		name: 'lastseen',
		signal: 'traces',
		fieldContext: '',
		fieldDataType: 'number',
		queryName: 'lastseen',
		aggregationIndex: 0,
		meta: {},
		columnType: 'metric',
	},
];
