/* eslint-disable sonarjs/no-duplicate-string */
import { PANEL_TYPES } from 'constants/queryBuilder';
import { GetQueryResultsProps } from 'lib/dashboard/getQueryResults';
import { DataTypes } from 'types/api/queryBuilder/queryAutocompleteResponse';
import { EQueryType } from 'types/common/dashboard';
import { DataSource } from 'types/common/queryBuilder';

// export const getQueryPayload = (
// 	clusterName: string,
// 	podName: string,
// ): GetQueryResultsProps[] => [
// 	{
// 		selectedTime: 'GLOBAL_TIME',
// 		graphType: PANEL_TYPES.TIME_SERIES,
// 		query: {
// 			builder: {
// 				queryData: [
// 					{
// 						aggregateAttribute: {
// 							dataType: DataTypes.Float64,
// 							id: 'k8s_pod_cpu_utilization--float64----true',
// 							isColumn: true,
// 							key: 'k8s_pod_cpu_utilization',
// 							type: '',
// 						},
// 						aggregateOperator: 'avg',
// 						dataSource: DataSource.METRICS,
// 						disabled: false,
// 						expression: 'A',
// 						filters: {
// 							items: [
// 								{
// 									id: '9a0ffaf3',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_cluster_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_cluster_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: clusterName,
// 								},
// 								{
// 									id: '9a0ffaf3',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_pod_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_pod_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: podName,
// 								},
// 							],
// 							op: 'AND',
// 						},
// 						groupBy: [
// 							{
// 								dataType: DataTypes.String,
// 								id: 'k8s_pod_name--string--tag--false',
// 								isColumn: false,
// 								key: 'k8s_pod_name',
// 								type: 'tag',
// 							},
// 						],
// 						having: [],
// 						legend: '{{k8s_pod_name}}',
// 						limit: null,
// 						orderBy: [],
// 						queryName: 'A',
// 						reduceTo: 'sum',
// 						spaceAggregation: 'sum',
// 						stepInterval: 60,
// 						timeAggregation: 'avg',
// 						functions: [],
// 					},
// 				],
// 				queryFormulas: [],
// 			},
// 			clickhouse_sql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			id: '3fe84db4-8f8b-44ba-b903-2daaab59c756',
// 			promql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			queryType: EQueryType.QUERY_BUILDER,
// 		},
// 		globalSelectedInterval: '3h',
// 		variables: {},
// 		formatForWeb: false,
// 	},
// 	{
// 		selectedTime: 'GLOBAL_TIME',
// 		graphType: PANEL_TYPES.TIME_SERIES,
// 		query: {
// 			builder: {
// 				queryData: [
// 					{
// 						aggregateAttribute: {
// 							dataType: DataTypes.Float64,
// 							id: 'k8s_pod_memory_usage--float64----true',
// 							isColumn: true,
// 							key: 'k8s_pod_memory_usage',
// 							type: '',
// 						},
// 						aggregateOperator: 'avg',
// 						dataSource: DataSource.METRICS,
// 						disabled: false,
// 						expression: 'A',
// 						filters: {
// 							items: [
// 								{
// 									id: '9a0ffaf3',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_cluster_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_cluster_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: clusterName,
// 								},
// 								{
// 									id: '2d8022f6',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_pod_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_pod_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: podName,
// 								},
// 							],
// 							op: 'AND',
// 						},
// 						groupBy: [
// 							{
// 								dataType: DataTypes.String,
// 								id: 'k8s_pod_name--string--tag--false',
// 								isColumn: false,
// 								key: 'k8s_pod_name',
// 								type: 'tag',
// 							},
// 						],
// 						having: [],
// 						legend: '{{k8s_pod_name}}',
// 						limit: null,
// 						orderBy: [],
// 						queryName: 'A',
// 						reduceTo: 'sum',
// 						spaceAggregation: 'sum',
// 						stepInterval: 60,
// 						timeAggregation: 'avg',
// 						functions: [],
// 					},
// 				],
// 				queryFormulas: [],
// 			},
// 			clickhouse_sql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			id: '59c73365-4180-4ddd-9406-2e2d8cfbc0d9',
// 			promql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			queryType: EQueryType.QUERY_BUILDER,
// 		},
// 		globalSelectedInterval: '3h',
// 		variables: {},
// 		formatForWeb: false,
// 	},
// 	{
// 		selectedTime: 'GLOBAL_TIME',
// 		graphType: PANEL_TYPES.TIME_SERIES,
// 		query: {
// 			builder: {
// 				queryData: [
// 					{
// 						aggregateAttribute: {
// 							dataType: DataTypes.Float64,
// 							id: 'k8s_pod_network_io--float64----true',
// 							isColumn: true,
// 							key: 'k8s_pod_network_io',
// 							type: '',
// 						},
// 						aggregateOperator: 'sum_rate',
// 						dataSource: DataSource.METRICS,
// 						disabled: false,
// 						expression: 'A',
// 						filters: {
// 							items: [
// 								{
// 									id: '9a0ffaf3',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_cluster_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_cluster_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: clusterName,
// 								},
// 								{
// 									id: 'c32821ed',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_pod_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_pod_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: podName,
// 								},
// 							],
// 							op: 'AND',
// 						},
// 						groupBy: [
// 							{
// 								dataType: DataTypes.String,
// 								id: 'direction--string--tag--false',
// 								isColumn: false,
// 								key: 'direction',
// 								type: 'tag',
// 							},
// 							{
// 								dataType: DataTypes.String,
// 								id: 'interface--string--tag--false',
// 								isColumn: false,
// 								key: 'interface',
// 								type: 'tag',
// 							},
// 							{
// 								dataType: DataTypes.String,
// 								id: 'k8s_pod_name--string--tag--false',
// 								isColumn: false,
// 								key: 'k8s_pod_name',
// 								type: 'tag',
// 							},
// 						],
// 						having: [],
// 						legend: '{{k8s_pod_name}}-{{interface}}-{{direction}}',
// 						limit: null,
// 						orderBy: [],
// 						queryName: 'A',
// 						reduceTo: 'sum',
// 						spaceAggregation: 'sum',
// 						stepInterval: 60,
// 						timeAggregation: 'rate',
// 						functions: [],
// 					},
// 				],
// 				queryFormulas: [],
// 			},
// 			clickhouse_sql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			id: '534b461d-d992-4a30-ba17-ed7aac95a55b',
// 			promql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			queryType: EQueryType.QUERY_BUILDER,
// 		},
// 		globalSelectedInterval: '3h',
// 		variables: {},
// 		formatForWeb: false,
// 	},
// 	{
// 		selectedTime: 'GLOBAL_TIME',
// 		graphType: PANEL_TYPES.TIME_SERIES,
// 		query: {
// 			builder: {
// 				queryData: [
// 					{
// 						aggregateAttribute: {
// 							dataType: DataTypes.Float64,
// 							id: 'k8s_pod_filesystem_usage--float64----true',
// 							isColumn: true,
// 							key: 'k8s_pod_filesystem_usage',
// 							type: '',
// 						},
// 						aggregateOperator: 'avg',
// 						dataSource: DataSource.METRICS,
// 						disabled: false,
// 						expression: 'A',
// 						filters: {
// 							items: [
// 								{
// 									id: '9a0ffaf3',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_cluster_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_cluster_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: clusterName,
// 								},
// 								{
// 									id: 'ba47cf47',
// 									key: {
// 										dataType: DataTypes.String,
// 										id: 'k8s_pod_name--string--tag--false',
// 										isColumn: false,
// 										key: 'k8s_pod_name',
// 										type: 'tag',
// 									},
// 									op: '=',
// 									value: podName,
// 								},
// 							],
// 							op: 'AND',
// 						},
// 						groupBy: [
// 							{
// 								dataType: DataTypes.String,
// 								id: 'k8s_pod_name--string--tag--false',
// 								isColumn: false,
// 								key: 'k8s_pod_name',
// 								type: 'tag',
// 							},
// 						],
// 						having: [],
// 						legend: '{{k8s_pod_name}}',
// 						limit: null,
// 						orderBy: [],
// 						queryName: 'A',
// 						reduceTo: 'sum',
// 						spaceAggregation: 'sum',
// 						stepInterval: 60,
// 						timeAggregation: 'avg',
// 						functions: [],
// 					},
// 				],
// 				queryFormulas: [],
// 			},
// 			clickhouse_sql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			id: '5a709367-ad0b-4a0a-9f7e-884e555f7686',
// 			promql: [
// 				{
// 					disabled: false,
// 					legend: '',
// 					name: 'A',
// 					query: '',
// 				},
// 			],
// 			queryType: EQueryType.QUERY_BUILDER,
// 		},
// 		globalSelectedInterval: '3h',
// 		variables: {},
// 		formatForWeb: false,
// 	},
// ];

export const getQueryPayload = (
	clusterName: string,
	podName: string,
): GetQueryResultsProps[] => [
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_cpu_utilization--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_cpu_utilization',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: '0a862947',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'cd13fbf0',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: 'usage - {{k8s_pod_name}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_container_cpu_limit--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_container_cpu_limit',
							type: 'Gauge',
						},
						aggregateOperator: 'latest',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: 'bfb8acf7',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'e09ba819',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_node_name}}'],
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: 'limit - {{k8s_pod_name}}',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'latest',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A*100/B',
						legend: '{{k8s_pod_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '6d5ccd81-0ea1-4fb9-a66b-7f0fe2f15165',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_pod_filesystem_available--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_pod_filesystem_available',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'c0f3e7ef',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'ae457343',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_pod_filesystem_capacity--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_pod_filesystem_capacity',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '8a387fb7',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '6ce28dde',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_node_name}}'],
								},
								{
									id: '3a50eee8',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_namespace_name--string--tag--false',
										isColumn: false,
										key: 'k8s_namespace_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_namespace_name}}'],
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: '(B-A)/B',
						legend: '{{k8s_pod_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: 'bbdc1096-339c-490c-a977-6eff00e3d72f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'ea3df3e7',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '39b21fe0',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_container_memory_request--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_container_memory_request',
							type: 'Gauge',
						},
						aggregateOperator: 'latest',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '7401a4b9',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '7cdad1cb',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
								{
									id: 'bd954dbe',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_namespace_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_namespace_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_namespace_name}}'],
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'latest',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A*100/B',
						legend: '{{k8s_pod_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '4d03a0ff-4fa5-4b19-b397-97f80ba9e0ac',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_pod_network_io--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_pod_network_io',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '877385bf',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '9613b4da',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'interface--string--tag--false',
								isColumn: false,
								key: 'interface',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'k8s_namespace_name--string--tag--false',
								isColumn: false,
								key: 'k8s_namespace_name',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend:
							'{{k8s_namespace_name}}-{{k8s_pod_name}}-{{interface}}-{{direction}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '4b255d6d-4cde-474d-8866-f4418583c18b',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_cpu_utilization--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_cpu_utilization',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: '8426b52f',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '2f67240c',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_container_cpu_request--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_container_cpu_request',
							type: 'Gauge',
						},
						aggregateOperator: 'latest',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '8c4667e1',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'b16e7306',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'latest',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A*100/B',
						legend: '{{k8s_pod_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '7bb3a6f5-d1c6-4f2e-9cc9-7dcc46db398f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'f2a3175c',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'fc17ff21',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_container_memory_limit--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_container_memory_limit',
							type: 'Gauge',
						},
						aggregateOperator: 'latest',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '175e96b7',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '1d9fbe48',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'latest',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A*100/B',
						legend: '{{k8s_pod_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: 'ad491f19-0f83-4dd4-bb8f-bec295c18d1b',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_cpu_utilization--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_cpu_utilization',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '6e050953',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '60fe5e62',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{k8s_pod_name}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '9b92756a-b445-45f8-90f4-d26f3ef28f8f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'container_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'container_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'a4250695',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '3b2bc32b',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_pod_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'k8s_pod_name',
										type: 'tag',
									},
									op: 'in',
									value: podName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_pod_name--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'k8s_pod_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{k8s_pod_name}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: 'a22c1e03-4876-4b3e-9a96-a3c3a28f9c0f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
];

export const getNodeQueryPayload = (
	clusterName: string,
	nodeName: string,
): GetQueryResultsProps[] => [
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_cpu_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_cpu_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: '{{.k8s_cluster_name}}',
								},
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_node_name}}'],
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{k8s_node_name}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_allocatable_cpu--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_allocatable_cpu',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: '{{.k8s_cluster_name}}',
								},
								{
									id: '0a54e48e',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: ['{{.k8s_node_name}}'],
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{k8s_node_name}}',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A/B',
						legend: '{{k8s_node_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '0a09fa11-6dc4-4511-9cc9-befe7b6a6557',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_filesystem_available--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_filesystem_available',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'a5dffef6',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: nodeName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_filesystem_capacity--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_filesystem_capacity',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'c79d5a16',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: nodeName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: '(B-A)/B',
						legend: '{{k8s_node_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '57eeac15-615c-4a71-9c61-8e0c0c76b045',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_memory_working_set--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_memory_working_set',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'e8c2a60a',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: nodeName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_allocatable_memory--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_allocatable_memory',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: 'ee687840',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: nodeName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A/B',
						legend: '{{k8s_node_name}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '4cf56615-e357-4342-9a4f-ec6557477ff3',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'k8s_node_network_io--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'k8s_node_network_io',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '91223422',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_cluster_name--string--tag--false',
										isColumn: false,
										key: 'k8s_cluster_name',
										type: 'tag',
									},
									op: '=',
									value: clusterName,
								},
								{
									id: '66308505',
									key: {
										dataType: DataTypes.String,
										id: 'k8s_node_name--string--tag--false',
										isColumn: false,
										key: 'k8s_node_name',
										type: 'tag',
									},
									op: 'in',
									value: nodeName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'interface--string--tag--false',
								isColumn: false,
								key: 'interface',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'k8s_node_name--string--tag--false',
								isColumn: false,
								key: 'k8s_node_name',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{k8s_node_name}}-{{interface}}-{{direction}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'sum',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: 'b56143c0-7d2f-4425-97c5-65ad6fc87366',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
];

export const getHostQueryPayload = (
	hostName: string,
): GetQueryResultsProps[] => [
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'b36d1580',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
								{
									id: '04c00b59',
									key: {
										dataType: DataTypes.String,
										id: 'state--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'state',
										type: 'tag',
									},
									op: '!=',
									value: 'idle',
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '9db53117',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A/B',
						legend: '',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '9bcfa405-fd17-42ea-a55e-2f9d42e5eeb5',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'a4a1f5a0',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
								{
									id: 'ee64c6c7',
									key: {
										dataType: DataTypes.String,
										id: 'state--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'state',
										type: 'tag',
									},
									op: '=',
									value: 'used',
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: 'bc3d98b1',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A/B',
						legend: '',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '94cd5a8e-4305-45b5-aeef-071e0943c00f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'ad316791',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'state--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'state',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{state}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: true,
						expression: 'B',
						filters: {
							items: [
								{
									id: '6baf116b',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '{{state}}',
						limit: null,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [
					{
						disabled: false,
						expression: 'A/B',
						legend: '{{state}}',
						queryName: 'F1',
					},
				],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '315b15fa-ff0c-442f-89f8-2bf4fb1af2f2',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_memory_usage--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_memory_usage',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '8026009e',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'state--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'state',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{state}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '40218bfb-a9b7-4974-aead-5bf666e139bf',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_load_average_1m--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_load_average_1m',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '4167fbb1',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '1m',
						limit: 30,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_load_average_5m--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_load_average_5m',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'B',
						filters: {
							items: [
								{
									id: '0c2cfeca',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '5m',
						limit: 30,
						orderBy: [],
						queryName: 'B',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_cpu_load_average_15m--float64--Gauge--true',
							isColumn: true,
							isJSON: false,
							key: 'system_cpu_load_average_15m',
							type: 'Gauge',
						},
						aggregateOperator: 'avg',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'C',
						filters: {
							items: [
								{
									id: '28693375',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '15m',
						limit: 30,
						orderBy: [],
						queryName: 'C',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'avg',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '8e6485ea-7018-43b0-ab27-b210f77b59ad',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_network_io--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_network_io',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '3a03bc80',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'device--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'device',
								type: 'tag',
							},
						],
						having: [
							{
								columnName: 'SUM(system_network_io)',
								op: '>',
								value: 0,
							},
						],
						legend: '{{device}}::{{direction}}',
						limit: 30,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '47173220-44df-4ef6-87f4-31e333c180c7',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_network_packets--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_network_packets',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '3082ef53',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'device--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'device',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{device}}::{{direction}}',
						limit: 30,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '62eedbc6-c8ad-4d13-80a8-129396e1d1dc',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_network_errors--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_network_errors',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '8859bc50',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'device--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'device',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{device}}::{{direction}}',
						limit: 30,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '5ddb1b38-53bb-46f5-b4fe-fe832d6b9b24',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_network_dropped--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_network_dropped',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '40fec2e3',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'direction',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'device--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'device',
								type: 'tag',
							},
						],
						having: [],
						legend: '{{device}}::{{direction}}',
						limit: 30,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: 'a849bcce-7684-4852-9134-530b45419b8f',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_disk_operation_time--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_disk_operation_time',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'd21dc017',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [
							{
								dataType: DataTypes.String,
								id: 'device--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'device',
								type: 'tag',
							},
							{
								dataType: DataTypes.String,
								id: 'direction--string--tag--false',
								isColumn: false,
								isJSON: false,
								key: 'direction',
								type: 'tag',
							},
						],
						having: [
							{
								columnName: 'SUM(system_disk_operation_time)',
								op: '>',
								value: 0,
							},
						],
						legend: '{{device}}::{{direction}}',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '9c6d18ad-89ff-4e38-a15a-440e72ed6ca8',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_disk_io--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_disk_io',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: '6039199f',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '9bd40b51-0790-4cdd-9718-551b2ded5926',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
	{
		selectedTime: 'GLOBAL_TIME',
		graphType: PANEL_TYPES.TIME_SERIES,
		query: {
			builder: {
				queryData: [
					{
						aggregateAttribute: {
							dataType: DataTypes.Float64,
							id: 'system_network_io--float64--Sum--true',
							isColumn: true,
							isJSON: false,
							key: 'system_network_io',
							type: 'Sum',
						},
						aggregateOperator: 'rate',
						dataSource: DataSource.METRICS,
						disabled: false,
						expression: 'A',
						filters: {
							items: [
								{
									id: 'e35cae4e',
									key: {
										dataType: DataTypes.String,
										id: 'host_name--string--tag--false',
										isColumn: false,
										isJSON: false,
										key: 'host_name',
										type: 'tag',
									},
									op: '=',
									value: hostName,
								},
							],
							op: 'AND',
						},
						functions: [],
						groupBy: [],
						having: [
							{
								columnName: 'SUM(system_network_io)',
								op: '>',
								value: 0,
							},
						],
						legend: '',
						limit: null,
						orderBy: [],
						queryName: 'A',
						reduceTo: 'avg',
						spaceAggregation: 'sum',
						stepInterval: 60,
						timeAggregation: 'rate',
					},
				],
				queryFormulas: [],
			},
			clickhouse_sql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			id: '6e58ef98-c680-4d28-a538-4b1ac71d3c37',
			promql: [
				{
					disabled: false,
					legend: '',
					name: 'A',
					query: '',
				},
			],
			queryType: EQueryType.QUERY_BUILDER,
		},
		globalSelectedInterval: '3h',
		variables: {},
		formatForWeb: false,
	},
];

export const cardTitles: string[] = [
	'Pod CPU usage',
	'Pod memory usage (WSS)',
	'Pod network IO',
	'Pod filesystem usage',
];

export const VIEW_TYPES = {
	NODE: 'node',
	POD: 'pod',
};

export const nodeCardTitles = [
	'Node CPU usage',
	'Node memory usage (WSS)',
	'Node network IO',
	'Node filesystem usage',
];
