const DEFAULT_FILTER_VALUE = '';
const EXCEPTION_TYPE_FILTER_NAME = 'exceptionType';
const SERVICE_NAME_FILTER_NAME = 'serviceName';
const COMPOSITE_QUERY_FILTER_NAME = 'compositeQuery';

export {
	COMPOSITE_QUERY_FILTER_NAME,
	DEFAULT_FILTER_VALUE,
	EXCEPTION_TYPE_FILTER_NAME,
	SERVICE_NAME_FILTER_NAME,
};
