package opamp

type ConfigDeploymentStatus struct {
	AgentId string

	// Received from RecommendedConfigGeneratorFn
	ConfigId string

	// Does this status represent a success or a failure.
	IsOk bool

	Description string
}

type AgentConfigProvider interface {
	// Generate recommended config for an agent based on its current `baseConfYaml`
	// and the latest settings for agent config based features.
	RecommendAgentConfig(baseConfYaml []byte) (
		recommendedConfYaml []byte,
		// Opaque id for recommended config, used for reporting deployment status updates
		configId string,
		err error,
	)

	// Report deployment status for config recommendations generated by RecommendAgentConfig
	ReportConfigDeploymentStatus(
		agentId string,
		configId string,
		status ConfigDeploymentStatus,
	)

	// Subscribe to be notified on changes in settings for agent config based features
	// Used for rolling out latest config recommendation to all connected agents when settings change
	SubscribeToConfigUpdates(callback func()) (unsubscribe func())
}
