// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package alertmanagertypestest

import (
	"context"
	"time"

	"github.com/SigNoz/signoz/pkg/types/alertmanagertypes"
	"github.com/SigNoz/signoz/pkg/valuer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMaintenanceStore creates a new instance of MockMaintenanceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMaintenanceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMaintenanceStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMaintenanceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMaintenanceStore is an autogenerated mock type for the MaintenanceStore type
type MockMaintenanceStore struct {
	mock.Mock
}

type MockMaintenanceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMaintenanceStore) EXPECT() *MockMaintenanceStore_Expecter {
	return &MockMaintenanceStore_Expecter{mock: &_m.Mock}
}

// CreatePlannedMaintenance provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) CreatePlannedMaintenance(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance) (*alertmanagertypes.PlannedMaintenance, error) {
	ret := _mock.Called(context1, postablePlannedMaintenance)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlannedMaintenance")
	}

	var r0 *alertmanagertypes.PlannedMaintenance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *alertmanagertypes.PostablePlannedMaintenance) (*alertmanagertypes.PlannedMaintenance, error)); ok {
		return returnFunc(context1, postablePlannedMaintenance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *alertmanagertypes.PostablePlannedMaintenance) *alertmanagertypes.PlannedMaintenance); ok {
		r0 = returnFunc(context1, postablePlannedMaintenance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alertmanagertypes.PlannedMaintenance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *alertmanagertypes.PostablePlannedMaintenance) error); ok {
		r1 = returnFunc(context1, postablePlannedMaintenance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_CreatePlannedMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlannedMaintenance'
type MockMaintenanceStore_CreatePlannedMaintenance_Call struct {
	*mock.Call
}

// CreatePlannedMaintenance is a helper method to define mock.On call
//   - context1 context.Context
//   - postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance
func (_e *MockMaintenanceStore_Expecter) CreatePlannedMaintenance(context1 any, postablePlannedMaintenance any) *MockMaintenanceStore_CreatePlannedMaintenance_Call {
	return &MockMaintenanceStore_CreatePlannedMaintenance_Call{Call: _e.mock.On("CreatePlannedMaintenance", context1, postablePlannedMaintenance)}
}

func (_c *MockMaintenanceStore_CreatePlannedMaintenance_Call) Run(run func(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance)) *MockMaintenanceStore_CreatePlannedMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *alertmanagertypes.PostablePlannedMaintenance
		if args[1] != nil {
			arg1 = args[1].(*alertmanagertypes.PostablePlannedMaintenance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_CreatePlannedMaintenance_Call) Return(plannedMaintenance *alertmanagertypes.PlannedMaintenance, err error) *MockMaintenanceStore_CreatePlannedMaintenance_Call {
	_c.Call.Return(plannedMaintenance, err)
	return _c
}

func (_c *MockMaintenanceStore_CreatePlannedMaintenance_Call) RunAndReturn(run func(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance) (*alertmanagertypes.PlannedMaintenance, error)) *MockMaintenanceStore_CreatePlannedMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAdhocPlannedMaintenanceByRule provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) DeleteAdhocPlannedMaintenanceByRule(context1 context.Context, s string, uUID valuer.UUID) (int64, error) {
	ret := _mock.Called(context1, s, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAdhocPlannedMaintenanceByRule")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, valuer.UUID) (int64, error)); ok {
		return returnFunc(context1, s, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, valuer.UUID) int64); ok {
		r0 = returnFunc(context1, s, uUID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, valuer.UUID) error); ok {
		r1 = returnFunc(context1, s, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAdhocPlannedMaintenanceByRule'
type MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call struct {
	*mock.Call
}

// DeleteAdhocPlannedMaintenanceByRule is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - uUID valuer.UUID
func (_e *MockMaintenanceStore_Expecter) DeleteAdhocPlannedMaintenanceByRule(context1 any, s any, uUID any) *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call {
	return &MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call{Call: _e.mock.On("DeleteAdhocPlannedMaintenanceByRule", context1, s, uUID)}
}

func (_c *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call) Run(run func(context1 context.Context, s string, uUID valuer.UUID)) *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 valuer.UUID
		if args[2] != nil {
			arg2 = args[2].(valuer.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call) Return(n int64, err error) *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call) RunAndReturn(run func(context1 context.Context, s string, uUID valuer.UUID) (int64, error)) *MockMaintenanceStore_DeleteAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlannedMaintenance provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) DeletePlannedMaintenance(context1 context.Context, uUID valuer.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlannedMaintenance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valuer.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMaintenanceStore_DeletePlannedMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlannedMaintenance'
type MockMaintenanceStore_DeletePlannedMaintenance_Call struct {
	*mock.Call
}

// DeletePlannedMaintenance is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID valuer.UUID
func (_e *MockMaintenanceStore_Expecter) DeletePlannedMaintenance(context1 any, uUID any) *MockMaintenanceStore_DeletePlannedMaintenance_Call {
	return &MockMaintenanceStore_DeletePlannedMaintenance_Call{Call: _e.mock.On("DeletePlannedMaintenance", context1, uUID)}
}

func (_c *MockMaintenanceStore_DeletePlannedMaintenance_Call) Run(run func(context1 context.Context, uUID valuer.UUID)) *MockMaintenanceStore_DeletePlannedMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valuer.UUID
		if args[1] != nil {
			arg1 = args[1].(valuer.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_DeletePlannedMaintenance_Call) Return(err error) *MockMaintenanceStore_DeletePlannedMaintenance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMaintenanceStore_DeletePlannedMaintenance_Call) RunAndReturn(run func(context1 context.Context, uUID valuer.UUID) error) *MockMaintenanceStore_DeletePlannedMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlannedMaintenanceByID provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) GetPlannedMaintenanceByID(context1 context.Context, uUID valuer.UUID) (*alertmanagertypes.PlannedMaintenance, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlannedMaintenanceByID")
	}

	var r0 *alertmanagertypes.PlannedMaintenance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valuer.UUID) (*alertmanagertypes.PlannedMaintenance, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valuer.UUID) *alertmanagertypes.PlannedMaintenance); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alertmanagertypes.PlannedMaintenance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valuer.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_GetPlannedMaintenanceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlannedMaintenanceByID'
type MockMaintenanceStore_GetPlannedMaintenanceByID_Call struct {
	*mock.Call
}

// GetPlannedMaintenanceByID is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID valuer.UUID
func (_e *MockMaintenanceStore_Expecter) GetPlannedMaintenanceByID(context1 any, uUID any) *MockMaintenanceStore_GetPlannedMaintenanceByID_Call {
	return &MockMaintenanceStore_GetPlannedMaintenanceByID_Call{Call: _e.mock.On("GetPlannedMaintenanceByID", context1, uUID)}
}

func (_c *MockMaintenanceStore_GetPlannedMaintenanceByID_Call) Run(run func(context1 context.Context, uUID valuer.UUID)) *MockMaintenanceStore_GetPlannedMaintenanceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valuer.UUID
		if args[1] != nil {
			arg1 = args[1].(valuer.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_GetPlannedMaintenanceByID_Call) Return(plannedMaintenance *alertmanagertypes.PlannedMaintenance, err error) *MockMaintenanceStore_GetPlannedMaintenanceByID_Call {
	_c.Call.Return(plannedMaintenance, err)
	return _c
}

func (_c *MockMaintenanceStore_GetPlannedMaintenanceByID_Call) RunAndReturn(run func(context1 context.Context, uUID valuer.UUID) (*alertmanagertypes.PlannedMaintenance, error)) *MockMaintenanceStore_GetPlannedMaintenanceByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdhocPlannedMaintenanceByRule provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) ListAdhocPlannedMaintenanceByRule(context1 context.Context, s string, uUID valuer.UUID) ([]*alertmanagertypes.PlannedMaintenance, error) {
	ret := _mock.Called(context1, s, uUID)

	if len(ret) == 0 {
		panic("no return value specified for ListAdhocPlannedMaintenanceByRule")
	}

	var r0 []*alertmanagertypes.PlannedMaintenance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, valuer.UUID) ([]*alertmanagertypes.PlannedMaintenance, error)); ok {
		return returnFunc(context1, s, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, valuer.UUID) []*alertmanagertypes.PlannedMaintenance); ok {
		r0 = returnFunc(context1, s, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*alertmanagertypes.PlannedMaintenance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, valuer.UUID) error); ok {
		r1 = returnFunc(context1, s, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdhocPlannedMaintenanceByRule'
type MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call struct {
	*mock.Call
}

// ListAdhocPlannedMaintenanceByRule is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - uUID valuer.UUID
func (_e *MockMaintenanceStore_Expecter) ListAdhocPlannedMaintenanceByRule(context1 any, s any, uUID any) *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call {
	return &MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call{Call: _e.mock.On("ListAdhocPlannedMaintenanceByRule", context1, s, uUID)}
}

func (_c *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call) Run(run func(context1 context.Context, s string, uUID valuer.UUID)) *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 valuer.UUID
		if args[2] != nil {
			arg2 = args[2].(valuer.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call) Return(plannedMaintenances []*alertmanagertypes.PlannedMaintenance, err error) *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Return(plannedMaintenances, err)
	return _c
}

func (_c *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call) RunAndReturn(run func(context1 context.Context, s string, uUID valuer.UUID) ([]*alertmanagertypes.PlannedMaintenance, error)) *MockMaintenanceStore_ListAdhocPlannedMaintenanceByRule_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlannedMaintenance provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) ListPlannedMaintenance(context1 context.Context, s string) ([]*alertmanagertypes.PlannedMaintenance, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListPlannedMaintenance")
	}

	var r0 []*alertmanagertypes.PlannedMaintenance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*alertmanagertypes.PlannedMaintenance, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*alertmanagertypes.PlannedMaintenance); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*alertmanagertypes.PlannedMaintenance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_ListPlannedMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlannedMaintenance'
type MockMaintenanceStore_ListPlannedMaintenance_Call struct {
	*mock.Call
}

// ListPlannedMaintenance is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockMaintenanceStore_Expecter) ListPlannedMaintenance(context1 any, s any) *MockMaintenanceStore_ListPlannedMaintenance_Call {
	return &MockMaintenanceStore_ListPlannedMaintenance_Call{Call: _e.mock.On("ListPlannedMaintenance", context1, s)}
}

func (_c *MockMaintenanceStore_ListPlannedMaintenance_Call) Run(run func(context1 context.Context, s string)) *MockMaintenanceStore_ListPlannedMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_ListPlannedMaintenance_Call) Return(plannedMaintenances []*alertmanagertypes.PlannedMaintenance, err error) *MockMaintenanceStore_ListPlannedMaintenance_Call {
	_c.Call.Return(plannedMaintenances, err)
	return _c
}

func (_c *MockMaintenanceStore_ListPlannedMaintenance_Call) RunAndReturn(run func(context1 context.Context, s string) ([]*alertmanagertypes.PlannedMaintenance, error)) *MockMaintenanceStore_ListPlannedMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlannedMaintenance provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) UpdatePlannedMaintenance(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance, uUID valuer.UUID) error {
	ret := _mock.Called(context1, postablePlannedMaintenance, uUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlannedMaintenance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *alertmanagertypes.PostablePlannedMaintenance, valuer.UUID) error); ok {
		r0 = returnFunc(context1, postablePlannedMaintenance, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMaintenanceStore_UpdatePlannedMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlannedMaintenance'
type MockMaintenanceStore_UpdatePlannedMaintenance_Call struct {
	*mock.Call
}

// UpdatePlannedMaintenance is a helper method to define mock.On call
//   - context1 context.Context
//   - postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance
//   - uUID valuer.UUID
func (_e *MockMaintenanceStore_Expecter) UpdatePlannedMaintenance(context1 any, postablePlannedMaintenance any, uUID any) *MockMaintenanceStore_UpdatePlannedMaintenance_Call {
	return &MockMaintenanceStore_UpdatePlannedMaintenance_Call{Call: _e.mock.On("UpdatePlannedMaintenance", context1, postablePlannedMaintenance, uUID)}
}

func (_c *MockMaintenanceStore_UpdatePlannedMaintenance_Call) Run(run func(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance, uUID valuer.UUID)) *MockMaintenanceStore_UpdatePlannedMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *alertmanagertypes.PostablePlannedMaintenance
		if args[1] != nil {
			arg1 = args[1].(*alertmanagertypes.PostablePlannedMaintenance)
		}
		var arg2 valuer.UUID
		if args[2] != nil {
			arg2 = args[2].(valuer.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_UpdatePlannedMaintenance_Call) Return(err error) *MockMaintenanceStore_UpdatePlannedMaintenance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMaintenanceStore_UpdatePlannedMaintenance_Call) RunAndReturn(run func(context1 context.Context, postablePlannedMaintenance *alertmanagertypes.PostablePlannedMaintenance, uUID valuer.UUID) error) *MockMaintenanceStore_UpdatePlannedMaintenance_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAdhocPlannedMaintenance provides a mock function for the type MockMaintenanceStore
func (_mock *MockMaintenanceStore) UpsertAdhocPlannedMaintenance(context1 context.Context, uUID valuer.UUID, s string, time1 time.Time) (*alertmanagertypes.PlannedMaintenance, error) {
	ret := _mock.Called(context1, uUID, s, time1)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAdhocPlannedMaintenance")
	}

	var r0 *alertmanagertypes.PlannedMaintenance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, valuer.UUID, string, time.Time) (*alertmanagertypes.PlannedMaintenance, error)); ok {
		return returnFunc(context1, uUID, s, time1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, valuer.UUID, string, time.Time) *alertmanagertypes.PlannedMaintenance); ok {
		r0 = returnFunc(context1, uUID, s, time1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alertmanagertypes.PlannedMaintenance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, valuer.UUID, string, time.Time) error); ok {
		r1 = returnFunc(context1, uUID, s, time1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAdhocPlannedMaintenance'
type MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call struct {
	*mock.Call
}

// UpsertAdhocPlannedMaintenance is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID valuer.UUID
//   - s string
//   - time1 time.Time
func (_e *MockMaintenanceStore_Expecter) UpsertAdhocPlannedMaintenance(context1 any, uUID any, s any, time1 any) *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call {
	return &MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call{Call: _e.mock.On("UpsertAdhocPlannedMaintenance", context1, uUID, s, time1)}
}

func (_c *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call) Run(run func(context1 context.Context, uUID valuer.UUID, s string, time1 time.Time)) *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 valuer.UUID
		if args[1] != nil {
			arg1 = args[1].(valuer.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call) Return(plannedMaintenance *alertmanagertypes.PlannedMaintenance, err error) *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call {
	_c.Call.Return(plannedMaintenance, err)
	return _c
}

func (_c *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call) RunAndReturn(run func(context1 context.Context, uUID valuer.UUID, s string, time1 time.Time) (*alertmanagertypes.PlannedMaintenance, error)) *MockMaintenanceStore_UpsertAdhocPlannedMaintenance_Call {
	_c.Call.Return(run)
	return _c
}
