package cmd

import (
	"bytes"
	"context"
	"os"
	"sort"
	"text/template"

	"github.com/SigNoz/signoz/pkg/types/coretypes"
	"github.com/spf13/cobra"
)

const permissionsTypePath = "frontend/src/hooks/useAuthZ/permissions.type.ts"

var permissionsTypeTemplate = template.Must(template.New("permissions").Parse(
	`// AUTO GENERATED FILE - DO NOT EDIT - GENERATED BY cmd/enterprise/*.go generate authz
export default {
	status: 'success',
	data: {
		resources: [
{{- range .Resources }}
			{
				kind: '{{ .Kind }}',
				type: '{{ .Type }}',
			},
{{- end }}
		],
		relations: {
{{- range .Relations }}
			{{ .Verb }}: [{{ range $i, $t := .Types }}{{ if $i }}, {{ end }}'{{ $t }}'{{ end }}],
{{- end }}
		},
	},
} as const;
`))

type permissionsTypeRelation struct {
	Verb  string
	Types []string
}

type permissionsTypeResource struct {
	Kind string
	Type string
}

type permissionsTypeData struct {
	Resources []permissionsTypeResource
	Relations []permissionsTypeRelation
}

func registerGenerateAuthz(parentCmd *cobra.Command) {
	authzCmd := &cobra.Command{
		Use:   "authz",
		Short: "Generate authz permissions for the frontend",
		RunE: func(currCmd *cobra.Command, args []string) error {
			return runGenerateAuthz(currCmd.Context())
		},
	}

	parentCmd.AddCommand(authzCmd)
}

func runGenerateAuthz(_ context.Context) error {
	registry := coretypes.NewRegistry()

	allowedResources := map[string]bool{
		coretypes.NewResourceRef(coretypes.ResourceServiceAccount).String():              true,
		coretypes.NewResourceRef(coretypes.ResourceMetaResourcesServiceAccount).String(): true,
		coretypes.NewResourceRef(coretypes.ResourceRole).String():                        true,
		coretypes.NewResourceRef(coretypes.ResourceMetaResourcesRole).String():           true,
	}

	allowedTypes := map[string]bool{}

	refs := registry.ResourceRefs()
	resources := make([]permissionsTypeResource, 0, len(refs))
	for _, ref := range refs {
		if !allowedResources[ref.String()] {
			continue
		}
		allowedTypes[ref.Type.StringValue()] = true
		resources = append(resources, permissionsTypeResource{
			Kind: ref.Kind.String(),
			Type: ref.Type.StringValue(),
		})
	}

	typesByVerb := registry.TypesByVerb()
	verbs := make([]coretypes.Verb, 0, len(typesByVerb))
	for verb := range typesByVerb {
		verbs = append(verbs, verb)
	}
	sort.Slice(verbs, func(i, j int) bool { return verbs[i].StringValue() < verbs[j].StringValue() })

	relations := make([]permissionsTypeRelation, 0, len(verbs))
	for _, verb := range verbs {
		types := make([]string, 0, len(typesByVerb[verb]))
		for _, t := range typesByVerb[verb] {
			if !allowedTypes[t.StringValue()] {
				continue
			}
			types = append(types, t.StringValue())
		}
		relations = append(relations, permissionsTypeRelation{
			Verb:  verb.StringValue(),
			Types: types,
		})
	}

	var buf bytes.Buffer
	if err := permissionsTypeTemplate.Execute(&buf, permissionsTypeData{Resources: resources, Relations: relations}); err != nil {
		return err
	}

	return os.WriteFile(permissionsTypePath, buf.Bytes(), 0o600)
}
