package cmd

import (
	"bytes"
	"context"
	"os"
	"sort"
	"text/template"

	"github.com/SigNoz/signoz/pkg/types/coretypes"
	"github.com/spf13/cobra"
)

const permissionsTypePath = "frontend/src/hooks/useAuthZ/permissions.type.ts"

var permissionsTypeTemplate = template.Must(template.New("permissions").Parse(
	`// AUTO GENERATED FILE - DO NOT EDIT - GENERATED BY cmd/enterprise/*.go generate authz
export default {
	status: 'success',
	data: {
		resources: [
{{- range .Resources }}
			{
				kind: '{{ .Kind }}',
				type: '{{ .Type }}',
			},
{{- end }}
		],
		relations: {
{{- range .Relations }}
			{{ .Verb }}: [{{ range $i, $t := .Types }}{{ if $i }}, {{ end }}'{{ $t }}'{{ end }}],
{{- end }}
		},
	},
} as const;
`))

type permissionsTypeRelation struct {
	Verb  string
	Types []string
}

type permissionsTypeResource struct {
	Kind string
	Type string
}

type permissionsTypeData struct {
	Resources []permissionsTypeResource
	Relations []permissionsTypeRelation
}

func registerGenerateAuthz(parentCmd *cobra.Command) {
	authzCmd := &cobra.Command{
		Use:   "authz",
		Short: "Generate authz permissions for the frontend",
		RunE: func(currCmd *cobra.Command, args []string) error {
			return runGenerateAuthz(currCmd.Context())
		},
	}

	parentCmd.AddCommand(authzCmd)
}

func runGenerateAuthz(_ context.Context) error {
	resources := coretypes.ListResources()
	verbsForTypes := coretypes.VerbsForTypes()

	data := permissionsTypeData{
		Resources: make([]permissionsTypeResource, 0, len(resources)),
		Relations: make([]permissionsTypeRelation, 0, len(verbsForTypes)),
	}

	for _, r := range resources {
		data.Resources = append(data.Resources, permissionsTypeResource{
			Kind: r.Kind.String(),
			Type: r.Type.StringValue(),
		})
	}

	verbs := make([]coretypes.Verb, 0, len(verbsForTypes))
	for verb := range verbsForTypes {
		verbs = append(verbs, verb)
	}
	sort.Slice(verbs, func(i, j int) bool { return verbs[i].StringValue() < verbs[j].StringValue() })

	for _, verb := range verbs {
		types := make([]string, 0, len(verbsForTypes[verb]))
		for _, t := range verbsForTypes[verb] {
			types = append(types, t.StringValue())
		}
		data.Relations = append(data.Relations, permissionsTypeRelation{
			Verb:  verb.StringValue(),
			Types: types,
		})
	}

	var buf bytes.Buffer
	if err := permissionsTypeTemplate.Execute(&buf, data); err != nil {
		return err
	}

	return os.WriteFile(permissionsTypePath, buf.Bytes(), 0o600)
}
