import os
from pathlib import Path

import pytest

from fixtures import types
from fixtures.auth import USER_ADMIN_EMAIL, USER_ADMIN_PASSWORD


def _env_file(pytestconfig: pytest.Config) -> Path:
    override = os.environ.get("SIGNOZ_E2E_ENV_FILE")
    if override:
        return Path(override)
    return pytestconfig.rootpath / "e2e" / ".env.local"


def test_setup(
    signoz: types.SigNoz,
    create_user_admin: types.Operation,  # pylint: disable=unused-argument
    apply_license: types.Operation,  # pylint: disable=unused-argument
    seeder: types.TestContainerDocker,
    pytestconfig: pytest.Config,
) -> None:
    """
    Bring the SigNoz backend up, register the admin, start the HTTP seeder
    container, and persist endpoint coordinates for the Playwright side as
    .env.local (loaded by playwright.config.ts via dotenv; overrides the
    user-owned .env). Each spec owns its own data via the seeder — no
    global pre-seed here.
    """
    host_cfg = signoz.self.host_configs["8080"]
    seeder_cfg = seeder.host_configs["8080"]
    out = _env_file(pytestconfig)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Generated by tests/e2e/bootstrap/setup.py — do not edit.\n"
        f"SIGNOZ_E2E_BASE_URL={host_cfg.base()}\n"
        f"SIGNOZ_E2E_USERNAME={USER_ADMIN_EMAIL}\n"
        f"SIGNOZ_E2E_PASSWORD={USER_ADMIN_PASSWORD}\n"
        f"SIGNOZ_E2E_SEEDER_URL={seeder_cfg.base()}\n"
    )


def test_teardown(
    signoz: types.SigNoz,  # pylint: disable=unused-argument
    create_user_admin: types.Operation,  # pylint: disable=unused-argument
    apply_license: types.Operation,  # pylint: disable=unused-argument
    seeder: types.TestContainerDocker,  # pylint: disable=unused-argument
) -> None:
    """Companion to test_setup — invoked with --teardown to free containers."""
