// file is generated by AI
package cloudintegrationtypes

import (
	"fmt"
	"strings"
	"testing"

	"github.com/SigNoz/signoz/pkg/valuer"
)

var testDeployParams = azureDeployParams{
	templateURL:        fmt.Sprintf(AgentArmTemplateStorePath.StringValue(), "v0.1.0"),
	location:           "eastus",
	signozAPIKey:       "test-api-key",
	signozAPIUrl:       "https://signoz.example.com",
	signozIngestionURL: "https://ingest.example.com",
	signozIngestionKey: "test-ingest-key",
	accountID:          "acct-123",
	agentVersion:       "v0.1.0",
}

func TestNewAzureConnectionCLICommand(t *testing.T) {
	cmd := newAzureConnectionCLICommand(testDeployParams)

	mustContain := []string{
		"az stack sub create",
		fmt.Sprintf("--name %s", AgentDeploymentStackName.StringValue()),
		fmt.Sprintf("--location %s", testDeployParams.location),
		fmt.Sprintf("--template-uri %s", testDeployParams.templateURL),
		fmt.Sprintf("%s='%s'", armParamLocation.StringValue(), testDeployParams.location),
		fmt.Sprintf("%s='%s'", armParamSignozAPIKey.StringValue(), testDeployParams.signozAPIKey),
		fmt.Sprintf("%s='%s'", armParamSignozAPIUrl.StringValue(), testDeployParams.signozAPIUrl),
		fmt.Sprintf("%s='%s'", armParamSignozIngestionURL.StringValue(), testDeployParams.signozIngestionURL),
		fmt.Sprintf("%s='%s'", armParamSignozIngestionKey.StringValue(), testDeployParams.signozIngestionKey),
		fmt.Sprintf("%s='%s'", armParamAccountID.StringValue(), testDeployParams.accountID),
		fmt.Sprintf("%s='%s'", armParamAgentVersion.StringValue(), testDeployParams.agentVersion),
		"--action-on-unmanage deleteAll",
		"--deny-settings-mode denyDelete",
	}

	for _, fragment := range mustContain {
		if !strings.Contains(cmd, fragment) {
			t.Errorf("CLI command missing %q\ngot:\n%s", fragment, cmd)
		}
	}

	// Lines must be joined with the bash line-continuation separator.
	if !strings.Contains(cmd, " \\\n") {
		t.Errorf("CLI command missing line-continuation separator ' \\\\\\n'\ngot:\n%s", cmd)
	}
}

func TestNewAzureConnectionPowerShellCommand(t *testing.T) {
	cmd := newAzureConnectionPowerShellCommand(testDeployParams)

	mustContain := []string{
		"New-AzSubscriptionDeploymentStack",
		fmt.Sprintf("-Name \"%s\"", AgentDeploymentStackName.StringValue()),
		fmt.Sprintf("-Location \"%s\"", testDeployParams.location),
		fmt.Sprintf("-TemplateUri \"%s\"", testDeployParams.templateURL),
		armParamLocation.StringValue(),
		armParamSignozAPIKey.StringValue(),
		armParamSignozAPIUrl.StringValue(),
		armParamSignozIngestionURL.StringValue(),
		armParamSignozIngestionKey.StringValue(),
		armParamAccountID.StringValue(),
		armParamAgentVersion.StringValue(),
		armParamRgName.StringValue(),
		armParamContainerEnvName.StringValue(),
		armParamDeploymentEnv.StringValue(),
		armDefaultRgName.StringValue(),
		armDefaultContainerEnvName.StringValue(),
		armDefaultDeploymentEnv.StringValue(),
		"-ActionOnUnmanage \"deleteAll\"",
		"-DenySettingsMode \"denyDelete\"",
	}

	for _, fragment := range mustContain {
		if !strings.Contains(cmd, fragment) {
			t.Errorf("PowerShell command missing %q\ngot:\n%s", fragment, cmd)
		}
	}

	// Final command must not end with a line-continuation backtick.
	if strings.HasSuffix(strings.TrimSpace(cmd), "`") {
		t.Errorf("PowerShell command must not end with a backtick\ngot:\n%s", cmd)
	}
}

func TestNewAzureConnectionArtifact(t *testing.T) {
	accountID := valuer.GenerateUUID()
	agentVersion := "v0.1.0"
	creds := &Credentials{
		SigNozAPIURL: "https://signoz.example.com",
		SigNozAPIKey: "test-api-key",
		IngestionURL: "https://ingest.example.com",
		IngestionKey: "test-ingest-key",
	}
	cfg := &AzurePostableAccountConfig{
		DeploymentRegion: "eastus",
		ResourceGroups:   []string{"rg1"},
	}

	artifact := NewAzureConnectionArtifact(accountID, agentVersion, creds, cfg)

	if artifact.CLICommand == "" {
		t.Error("CLICommand must not be empty")
	}
	if artifact.CloudPowerShellCommand == "" {
		t.Error("CloudPowerShellCommand must not be empty")
	}
	if !strings.Contains(artifact.CLICommand, accountID.StringValue()) {
		t.Errorf("CLICommand must contain accountID %q", accountID.StringValue())
	}
	if !strings.Contains(artifact.CloudPowerShellCommand, accountID.StringValue()) {
		t.Errorf("CloudPowerShellCommand must contain accountID %q", accountID.StringValue())
	}
}
