package slo

import (
	"crypto/rand"
	"fmt"
)

const DashboardTitle = "SLOs & Error Budgets [sre-sidekick]"

func BuildDashboard() map[string]any {
	panels := []struct {
		title string
		query string
		unit  string
	}{
		{"SLO Compliance", "slo_compliance", "percentunit"},
		{"Error Budget Remaining", "slo_error_budget_remaining", "percentunit"},
		{"Burn Rate", "slo_burn_rate", ""},
		{"Trust State (0 unhealthy, 1 healthy, 2 indeterminate)", "slo_state", ""},
		{"Multi-window Burn Firing", "slo_mwmb_firing", ""},
		{"Telemetry Quality Score", "telemetry_quality_score", ""},
		{"Telemetry Quality Coverage", "telemetry_quality_coverage", "percentunit"},
		{"Telemetry Findings", "telemetry_quality_findings", ""},
	}
	widgets := make([]any, 0, len(panels))
	layout := make([]any, 0, len(panels))
	for i, panel := range panels {
		id := newID()
		widgets = append(widgets, map[string]any{
			"id": id, "title": panel.title, "panelTypes": "graph", "yAxisUnit": panel.unit,
			"query": map[string]any{
				"queryType":      "promql",
				"promql":         []any{map[string]any{"name": "A", "query": panel.query, "legend": "{{slo}}", "disabled": false}},
				"builder":        map[string]any{"queryData": []any{}, "queryFormulas": []any{}},
				"clickhouse_sql": []any{}, "id": newID(),
			},
		})
		layout = append(layout, map[string]any{"i": id, "x": (i % 2) * 6, "y": (i / 2) * 6, "w": 6, "h": 6})
	}
	return map[string]any{
		"title":       DashboardTitle,
		"description": "Generated by sre-sidekick: SLO, error budget, burn rate, and trust state.",
		"tags":        []any{"slo", "generated"}, "version": "v4", "variables": map[string]any{},
		"layout": layout, "widgets": widgets,
	}
}

func newID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return fmt.Sprintf("00000000-0000-4000-8000-%012x", b[0:6])
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
