# This workflow will inspect a pull request to ensure there is a linked issue or a
# valid issue is mentioned in the body. If neither is present it fails the check and adds
# a comment alerting users of this missing requirement.
name: VerifyIssue

on:
  pull_request:
    types: [edited, opened]
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: srikanthccv/verify-linked-issue-action@v0.71
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
