name: releaser

on:
  # trigger on new latest release
  release:
    types: [published]

jobs:
  charts:
    runs-on: ubuntu-latest
    steps:
      - id: token
        name: github-token-gen
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRIMUS_APP_ID }}
          private-key: ${{ secrets.PRIMUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: trigger-charts-prereleaser
        run: |
          # Variables
          repo_owner="signoz"
          repo_name="charts"
          event_type="prereleaser"

          # identify the release type
          release_tag=${{ github.event.release.tag_name }}
          patch_number=$(echo $release_tag | awk -F. '{print $3}')
          release_type="minor"
          if [[ $patch_number -ne 0 ]]; then
            release_type="patch"
          fi

          # trigger the releaser workflow in signoz/charts repo
          curl -L -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            "https://api.github.com/repos/${repo_owner}/${repo_name}/dispatches" \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"release_type\": \"$release_type\"}}"
