name: releaser-signoz

on:
  # schedule every wednesday 9:30 AM UTC (3pm IST)
  schedule:
    - cron: '30 9 * * 3'

  # allow manual triggering of the workflow by a maintainer with no inputs
  workflow_dispatch:
    inputs:
      release_type:
        description: "Type of the release"
        type: choice
        required: true
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  signoz:
    uses: signoz/primus.workflows/.github/workflows/releaser.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      PROJECT_NAME: signoz
      RELEASE_TYPE: ${{ inputs.release_type || 'minor' }}
