name: remove-label

on:
  pull_request_target:
    types: [synchronize]

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove label testing-deploy from PR
        uses: buildsville/add-remove-label@v2.0.0
        with:
          label: testing-deploy
          type: remove
          token: ${{ secrets.GITHUB_TOKEN }}
