name: Run E2E (Playwright) Tests

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        description: "Base URL of the app (e.g., https://app.us.staging.signoz.cloud)"
        required: true
        type: string
      username:
        description: "Username for login"
        required: true
        type: string
      password:
        description: "Password for login"
        required: true
        type: string
      userRole:
        description: "Role of the user (ADMIN, EDITOR, VIEWER, SIGNOZ_ADMIN)"
        required: true
        type: choice
        options:
          - ADMIN
          - EDITOR
          - VIEWER
          - SIGNOZ_ADMIN

jobs:
  test:
    name: Run Playwright Tests Manually
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          echo "Running Playwright tests..."
          echo "BASE_URL: ${{ github.event.inputs.baseUrl }}"
          echo "USER_ROLE: ${{ github.event.inputs.userRole }}"

          BASE_URL="${{ github.event.inputs.baseUrl }}" \
          LOGIN_USERNAME="${{ github.event.inputs.username }}" \
          LOGIN_PASSWORD="${{ github.event.inputs.password }}" \
          USER_ROLE="${{ github.event.inputs.userRole }}" \
          yarn playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
