name: e2eci

on:
  workflow_dispatch:
    inputs:
      userRole:
        description: "Role of the user (ADMIN, EDITOR, VIEWER)"
        required: true
        type: choice
        options:
          - ADMIN
          - EDITOR
          - VIEWER

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Mask secrets and inputs
        run: |
          echo "::add-mask::${{ secrets.E2E_TENANT_BASE_URL }}"
          echo "::add-mask::${{ secrets.E2E_USER_EMAIL }}"
          echo "::add-mask::${{ secrets.E2E_USER_PASSWORD }}"
          echo "::add-mask::${{ github.event.inputs.userRole }}"

      - name: Run Playwright Tests
        run: |
          echo "✅ Starting Playwright tests..."

          BASE_URL="${{ secrets.E2E_TENANT_BASE_URL }}" \
          LOGIN_USERNAME="${{ secrets.E2E_USER_EMAIL }}" \
          LOGIN_PASSWORD="${{ secrets.E2E_USER_PASSWORD }}" \
          USER_ROLE="${{ github.event.inputs.userRole }}" \
          yarn playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
