name: Run E2E (Playwright) Tests

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        description: "Base URL of the app (e.g., https://app.us.staging.signoz.cloud)"
        required: true
        type: string
      userRole:
        description: "Role of the user (ADMIN, EDITOR, VIEWER)"
        required: true
        type: choice
        options:
          - ADMIN
          - EDITOR
          - VIEWER

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Mask sensitive inputs and secrets
        run: |
          echo "::add-mask::${{ github.event.inputs.baseUrl }}"
          echo "::add-mask::${{ github.event.inputs.userRole }}"
          echo "::add-mask::${{ secrets.LOGIN_USERNAME }}"
          echo "::add-mask::${{ secrets.LOGIN_PASSWORD }}"

      - name: Run Playwright Tests
        run: |
          echo "✅ Starting Playwright tests..."

          BASE_URL="${{ github.event.inputs.baseUrl }}" \
          USER_ROLE="${{ github.event.inputs.userRole }}" \

          yarn playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
